import { useState } from "react";
import { ArrowLeft, ArrowRight, Download, Edit2, ReceiptText, Users } from "lucide-react";
import "./_group.css";

export function ReceiptDetail() {
  const [editingShare, setEditingShare] = useState(false);
  return <div className="receiptify-current min-h-screen bg-gray-50 pb-24">
    <header className="flex items-center justify-between border-b border-gray-100 bg-white px-6 py-4"><button className="w-9 p-2"><ArrowLeft className="h-5 w-5 text-gray-700" /></button><div className="text-center"><h1 className="text-2xl font-bold text-green-800">Receiptify</h1><p className="text-xs text-gray-600">Your Digital Wallet</p></div><div className="w-9" /></header>
    <main className="mx-auto max-w-xl space-y-6 px-6 py-4">
      <section className="flex items-start justify-between gap-3"><div><h2 className="mb-2 text-2xl font-bold text-gray-900">Sainsbury&apos;s</h2><p className="text-gray-600">18 Mar 2025, 03:42 PM • Islington, London</p></div><button className="inline-flex items-center rounded-md border border-gray-200 bg-white px-3 py-2 text-sm font-medium text-gray-700"><Edit2 className="mr-1 h-4 w-4" />Edit</button></section>
      <section><h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-gray-700">Receipt Image</h3><div className="flex aspect-[3/2] items-center justify-center rounded-[1.3rem] border border-gray-200 bg-white shadow-sm"><div className="w-44 rounded-sm bg-[#fffdf7] p-4 text-center font-mono text-[9px] leading-relaxed text-gray-600 shadow-md"><b className="block text-sm text-gray-800">SAINSBURY&apos;S</b><span>ISLINGTON LOCAL</span><hr className="my-2 border-dashed" /><p className="flex justify-between"><span>Taste the Difference</span><span>4.50</span></p><p className="flex justify-between"><span>British Chicken</span><span>6.75</span></p><p className="flex justify-between"><span>Fresh Produce</span><span>9.20</span></p><p className="flex justify-between"><span>Household essentials</span><span>15.30</span></p><hr className="my-2 border-dashed" /><b className="flex justify-between text-sm"><span>TOTAL</span><span>38.60</span></b><p className="mt-2">VISA •••• 4242</p></div></div></section>
      <section className="rounded-[1.3rem] bg-white p-6 shadow-sm"><div className="space-y-4 text-gray-900"><Item name="Taste the Difference Orange Juice" price="£4.50" /><Item name="British Chicken Breast Fillets" price="£6.75" /><Item name="2x Sainsbury's Strawberries" price="£6.00" /><Item name="Kitchen Roll" price="£5.25" /><Item name="Other groceries" price="£10.10" /><div className="mt-4 border-t border-gray-200 pt-4"><Row label="Subtotal" value="£32.17" /></div><div className="border-t border-gray-200 pt-4"><Row label="Tax" value="£6.43" /><div className="pt-3"><Row label="Total" value="£38.60" bold /></div></div></div></section>
      <section className="rounded-[1.3rem] bg-white p-4 shadow-sm"><div className="mb-1 flex items-center justify-between"><h3 className="font-semibold text-gray-900">My share</h3><button className="text-sm text-gray-500">Clear</button></div><p className="mb-3 text-xs text-gray-500">If you didn&apos;t pay the full amount, set your portion — totals in My Receipts and Analytics will use it instead of the full total.</p><div className="mb-3 flex items-center justify-between gap-2 rounded-lg border border-green-200 bg-green-50 px-3 py-2"><p className="text-xs text-green-800">From this receipt&apos;s split: <b>£22.40</b> is your portion after friends&apos; assignments.</p><button className="shrink-0 rounded-md bg-green-600 px-2 py-1.5 text-xs font-medium text-white">Use split amount</button></div>
      {editingShare ? <div className="space-y-3"><div className="flex gap-2"><select className="h-10 w-36 rounded-md border border-gray-200 px-2 text-sm"><option>Amount (GBP)</option><option>Percentage</option></select><input defaultValue="22.40" className="h-10 flex-1 rounded-md border border-gray-200 px-3 text-sm" /></div><p className="text-xs text-gray-500">Your share: £22.40</p><div className="flex justify-end gap-2"><button onClick={() => setEditingShare(false)} className="px-3 py-2 text-sm">Cancel</button><button onClick={() => setEditingShare(false)} className="rounded-md bg-green-600 px-3 py-2 text-sm text-white">Save</button></div></div> : <div className="flex items-center justify-between"><p className="text-sm text-gray-900"><b>£22.40</b> <span className="text-gray-500">(fixed amount)</span></p><button onClick={() => setEditingShare(true)} className="inline-flex items-center rounded-md border border-gray-200 px-3 py-2 text-sm"><Edit2 className="mr-1 h-4 w-4" />Edit</button></div>}</section>
      <section className="flex items-center justify-between rounded-[1.3rem] bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100"><Users className="h-5 w-5 text-green-600" /></span><div><h3 className="font-semibold text-gray-900">In a split folder</h3><p className="text-xs text-gray-500">Open the folder to edit who pays what</p></div></div><div className="flex gap-1"><button className="rounded-md border border-gray-200 px-3 py-2 text-sm">Move</button><button className="inline-flex items-center rounded-md bg-green-600 px-3 py-2 text-sm text-white">Open <ArrowRight className="ml-1 h-4 w-4" /></button></div></section>
      <section className="flex items-center justify-between rounded-[1.3rem] bg-white p-4 shadow-sm"><div><p className="text-sm text-gray-600">Download</p><p className="font-medium text-gray-900">Receipt Image</p></div><button className="inline-flex items-center rounded-md bg-green-800 px-3 py-2 text-sm text-white"><Download className="mr-2 h-4 w-4" />Download</button></section>
      <section className="flex items-center gap-3 rounded-[1.3rem] bg-white p-4 shadow-sm"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-green-100"><ReceiptText className="h-4 w-4 text-green-600" /></span><span className="font-medium text-gray-900">Groceries</span></section>
    </main>
  </div>;
}
function Item({ name, price }: { name: string; price: string }) { return <div className="flex items-center justify-between gap-3"><span className="font-medium">{name}</span><b>{price}</b></div>; }
function Row({ label, value, bold = false }: { label: string; value: string; bold?: boolean }) { return <div className={`flex justify-between ${bold ? "text-lg font-bold" : ""}`}><span>{label}</span><span>{value}</span></div>; }